server {
    listen 80;
    server_name _;

    # Visor estático (Leaflet).
    location / {
        root  /usr/share/nginx/html;
        index index.html;
    }

    # Backend FastAPI. Mismo origen que el visor -> sin CORS.
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # GeoServer (WMS para el visor). Mismo origen -> sin CORS.
    location /geoserver/ {
        proxy_pass http://geoserver:8080/geoserver/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
